#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

#------------------------------- hemodynamic4Foam project -------------------------------#
#Author
    #Ehsan Golab, SUT. All rights reserved.
    #Ehsan1996Golab@gmail.com

#--------------------------------------------------------------------------------------#

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# cleancase is function that removes the files and directories.(rm -f : remove the file, rm -r : remove the directory).
cleancase ()
{
    rm -r Gnu*
    rm -r processor*
}

# (getApplication) is an command to find the solver name from the controlDict file. Also, ($) use for the variable.
application=$(getApplication)

#cleancase
#./Allclean


echo run blokMesh ...
#m4 -P constant/polyMesh/blockMeshDictConicalCylinder.m4 > constant/polyMesh/blockMeshDict
#m4 -P constant/polyMesh/blockMeshDictConicalCylinderAndExternalSquare.m4 > constant/polyMesh/blockMeshDict
#m4 -P constant/polyMesh/blockMeshDictConicalCylinderAndTrapezoidalSquare.m4 > constant/polyMesh/blockMeshDict
#m4 -P constant/polyMesh/blockMeshDictConicalCylinderCHT.m4 > constant/polyMesh/blockMeshDict
#m4 -P constant/polyMesh/blockMeshDictConicalRectangular.m4 > constant/polyMesh/blockMeshDict

#m4 -P constant/polyMesh/blockMeshDictHollowCone.m4 > constant/polyMesh/blockMeshDict
#m4 -P constant/polyMesh/blockMeshDictSemiAnnulus.m4 > constant/polyMesh/blockMeshDict
#m4 -P constant/polyMesh/blockMeshDictSemiCylinder.m4 > constant/polyMesh/blockMeshDict
#m4 -P constant/polyMesh/blockMeshDictTrapezoid.m4 > constant/polyMesh/blockMeshDict
m4 -P constant/polyMesh/blockMeshDictTrapezoidSymmetry.m4 > constant/polyMesh/blockMeshDict


blockMesh
#checkMesh
# -------------------------------------------------------------------------- end-of-file
